/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardProductsRouteRouteImport } from './routes/_dashboard/products/route'
import { Route as DashboardProductsProductIdRouteImport } from './routes/_dashboard/products/$productId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsRouteRoute = DashboardProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsProductIdRoute =
  DashboardProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => DashboardProductsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/organizations': typeof OrganizationsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/products': typeof DashboardProductsRouteRouteWithChildren
  '/products/$productId': typeof DashboardProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/organizations': typeof OrganizationsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/products': typeof DashboardProductsRouteRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/products/$productId': typeof DashboardProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/organizations': typeof OrganizationsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_dashboard/products': typeof DashboardProductsRouteRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/products/$productId': typeof DashboardProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizations'
    | '/signin'
    | '/signup'
    | '/products'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/organizations'
    | '/signin'
    | '/signup'
    | '/products'
    | '/'
    | '/products/$productId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/organizations'
    | '/signin'
    | '/signup'
    | '/_dashboard/products'
    | '/_dashboard/'
    | '/_dashboard/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OrganizationsRoute: typeof OrganizationsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products': {
      id: '/_dashboard/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashboardProductsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products/$productId': {
      id: '/_dashboard/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof DashboardProductsProductIdRouteImport
      parentRoute: typeof DashboardProductsRouteRoute
    }
  }
}

interface DashboardProductsRouteRouteChildren {
  DashboardProductsProductIdRoute: typeof DashboardProductsProductIdRoute
}

const DashboardProductsRouteRouteChildren: DashboardProductsRouteRouteChildren =
  {
    DashboardProductsProductIdRoute: DashboardProductsProductIdRoute,
  }

const DashboardProductsRouteRouteWithChildren =
  DashboardProductsRouteRoute._addFileChildren(
    DashboardProductsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardProductsRouteRoute: typeof DashboardProductsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProductsRouteRoute: DashboardProductsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OrganizationsRoute: OrganizationsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
