/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardWarehousesRouteRouteImport } from './routes/_dashboard/warehouses/route'
import { Route as DashboardProductsRouteRouteImport } from './routes/_dashboard/products/route'
import { Route as DashboardWarehousesIndexRouteImport } from './routes/_dashboard/warehouses/index'
import { Route as DashboardStockMovementsIndexRouteImport } from './routes/_dashboard/stock-movements/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/_dashboard/products/index'
import { Route as DashboardWarehousesWarehouseIdRouteImport } from './routes/_dashboard/warehouses/$warehouseId'
import { Route as DashboardStockMovementsMovementIdRouteImport } from './routes/_dashboard/stock-movements/$movementId'
import { Route as DashboardProductsProductIdRouteImport } from './routes/_dashboard/products/$productId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWarehousesRouteRoute =
  DashboardWarehousesRouteRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsRouteRoute = DashboardProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWarehousesIndexRoute =
  DashboardWarehousesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWarehousesRouteRoute,
  } as any)
const DashboardStockMovementsIndexRoute =
  DashboardStockMovementsIndexRouteImport.update({
    id: '/stock-movements/',
    path: '/stock-movements/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProductsRouteRoute,
} as any)
const DashboardWarehousesWarehouseIdRoute =
  DashboardWarehousesWarehouseIdRouteImport.update({
    id: '/$warehouseId',
    path: '/$warehouseId',
    getParentRoute: () => DashboardWarehousesRouteRoute,
  } as any)
const DashboardStockMovementsMovementIdRoute =
  DashboardStockMovementsMovementIdRouteImport.update({
    id: '/stock-movements/$movementId',
    path: '/stock-movements/$movementId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductsProductIdRoute =
  DashboardProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => DashboardProductsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/organizations': typeof OrganizationsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/products': typeof DashboardProductsRouteRouteWithChildren
  '/warehouses': typeof DashboardWarehousesRouteRouteWithChildren
  '/products/$productId': typeof DashboardProductsProductIdRoute
  '/stock-movements/$movementId': typeof DashboardStockMovementsMovementIdRoute
  '/warehouses/$warehouseId': typeof DashboardWarehousesWarehouseIdRoute
  '/products/': typeof DashboardProductsIndexRoute
  '/stock-movements/': typeof DashboardStockMovementsIndexRoute
  '/warehouses/': typeof DashboardWarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/organizations': typeof OrganizationsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/': typeof DashboardIndexRoute
  '/products/$productId': typeof DashboardProductsProductIdRoute
  '/stock-movements/$movementId': typeof DashboardStockMovementsMovementIdRoute
  '/warehouses/$warehouseId': typeof DashboardWarehousesWarehouseIdRoute
  '/products': typeof DashboardProductsIndexRoute
  '/stock-movements': typeof DashboardStockMovementsIndexRoute
  '/warehouses': typeof DashboardWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/organizations': typeof OrganizationsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_dashboard/products': typeof DashboardProductsRouteRouteWithChildren
  '/_dashboard/warehouses': typeof DashboardWarehousesRouteRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/products/$productId': typeof DashboardProductsProductIdRoute
  '/_dashboard/stock-movements/$movementId': typeof DashboardStockMovementsMovementIdRoute
  '/_dashboard/warehouses/$warehouseId': typeof DashboardWarehousesWarehouseIdRoute
  '/_dashboard/products/': typeof DashboardProductsIndexRoute
  '/_dashboard/stock-movements/': typeof DashboardStockMovementsIndexRoute
  '/_dashboard/warehouses/': typeof DashboardWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizations'
    | '/signin'
    | '/signup'
    | '/products'
    | '/warehouses'
    | '/products/$productId'
    | '/stock-movements/$movementId'
    | '/warehouses/$warehouseId'
    | '/products/'
    | '/stock-movements/'
    | '/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/organizations'
    | '/signin'
    | '/signup'
    | '/'
    | '/products/$productId'
    | '/stock-movements/$movementId'
    | '/warehouses/$warehouseId'
    | '/products'
    | '/stock-movements'
    | '/warehouses'
  id:
    | '__root__'
    | '/_dashboard'
    | '/organizations'
    | '/signin'
    | '/signup'
    | '/_dashboard/products'
    | '/_dashboard/warehouses'
    | '/_dashboard/'
    | '/_dashboard/products/$productId'
    | '/_dashboard/stock-movements/$movementId'
    | '/_dashboard/warehouses/$warehouseId'
    | '/_dashboard/products/'
    | '/_dashboard/stock-movements/'
    | '/_dashboard/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OrganizationsRoute: typeof OrganizationsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/warehouses': {
      id: '/_dashboard/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof DashboardWarehousesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products': {
      id: '/_dashboard/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DashboardProductsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/warehouses/': {
      id: '/_dashboard/warehouses/'
      path: '/'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof DashboardWarehousesIndexRouteImport
      parentRoute: typeof DashboardWarehousesRouteRoute
    }
    '/_dashboard/stock-movements/': {
      id: '/_dashboard/stock-movements/'
      path: '/stock-movements'
      fullPath: '/stock-movements/'
      preLoaderRoute: typeof DashboardStockMovementsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products/': {
      id: '/_dashboard/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardProductsRouteRoute
    }
    '/_dashboard/warehouses/$warehouseId': {
      id: '/_dashboard/warehouses/$warehouseId'
      path: '/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof DashboardWarehousesWarehouseIdRouteImport
      parentRoute: typeof DashboardWarehousesRouteRoute
    }
    '/_dashboard/stock-movements/$movementId': {
      id: '/_dashboard/stock-movements/$movementId'
      path: '/stock-movements/$movementId'
      fullPath: '/stock-movements/$movementId'
      preLoaderRoute: typeof DashboardStockMovementsMovementIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/products/$productId': {
      id: '/_dashboard/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof DashboardProductsProductIdRouteImport
      parentRoute: typeof DashboardProductsRouteRoute
    }
  }
}

interface DashboardProductsRouteRouteChildren {
  DashboardProductsProductIdRoute: typeof DashboardProductsProductIdRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
}

const DashboardProductsRouteRouteChildren: DashboardProductsRouteRouteChildren =
  {
    DashboardProductsProductIdRoute: DashboardProductsProductIdRoute,
    DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  }

const DashboardProductsRouteRouteWithChildren =
  DashboardProductsRouteRoute._addFileChildren(
    DashboardProductsRouteRouteChildren,
  )

interface DashboardWarehousesRouteRouteChildren {
  DashboardWarehousesWarehouseIdRoute: typeof DashboardWarehousesWarehouseIdRoute
  DashboardWarehousesIndexRoute: typeof DashboardWarehousesIndexRoute
}

const DashboardWarehousesRouteRouteChildren: DashboardWarehousesRouteRouteChildren =
  {
    DashboardWarehousesWarehouseIdRoute: DashboardWarehousesWarehouseIdRoute,
    DashboardWarehousesIndexRoute: DashboardWarehousesIndexRoute,
  }

const DashboardWarehousesRouteRouteWithChildren =
  DashboardWarehousesRouteRoute._addFileChildren(
    DashboardWarehousesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardProductsRouteRoute: typeof DashboardProductsRouteRouteWithChildren
  DashboardWarehousesRouteRoute: typeof DashboardWarehousesRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardStockMovementsMovementIdRoute: typeof DashboardStockMovementsMovementIdRoute
  DashboardStockMovementsIndexRoute: typeof DashboardStockMovementsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProductsRouteRoute: DashboardProductsRouteRouteWithChildren,
  DashboardWarehousesRouteRoute: DashboardWarehousesRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardStockMovementsMovementIdRoute:
    DashboardStockMovementsMovementIdRoute,
  DashboardStockMovementsIndexRoute: DashboardStockMovementsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OrganizationsRoute: OrganizationsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
